export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const TODO_ITEM_ADDED = 'TODO_ITEM_ADDED';

export const CHANGE_TODO_ITEM_CHECKED = 'CHANGE_TODO_ITEM_CHECKED';
export const TODO_ITEM_CHECKED_CHANGED = 'TODO_ITEM_CHECKED_CHANGED';

export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';

