export const GET_TODO_ITEMS = 'GET_TODO_ITEMS';
export const GET_TODO_FAILURE = 'GET_TODO_FAILURE';

export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const TODO_ITEM_ADDED = 'TODO_ITEM_ADDED';
export const ADD_TODO_ITEM_FAILURE = 'ADD_TODO_ITEM_FAILURE';

export const CHANGE_TODO_ITEM_CHECKED = 'CHANGE_TODO_ITEM_CHECKED';
export const TODO_ITEM_CHECKED_CHANGED = 'TODO_ITEM_CHECKED_CHANGED';

export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';
export const TODO_ITEM_EDITED = 'TODO_ITEM_EDITED';
export const EDIT_TODO_ITEM_FAILURE = 'EDIT_TODO_ITEM_FAILURE';

export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
